on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  pr:
    name: Release Zed Extension
    runs-on: ubuntu-slim
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: svelte-snippets
          push-to: bobbymannino/zed-extensions
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

  release:
    needs: pr
    name: Github Release
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: bobbymannino/github-release-action@v1
